#This is an initialization workflow for copying Node starter workflow and sample app (if required)
name: devsecops-init-unified-pipeline
on: 
  workflow_dispatch:
    inputs:
      STACK_NAME:
        type: choice
        description: 'Type in Java or Node'     
        required: true
        options: 
        - Node
        - Java
        default: 'Node'
      
      INCLUDE_SAMPLE_SRC:
        type: choice
        description: 'Do you need the sample source code to be included'     
        required: false
        options: 
        - 'false'
        - 'true'
        default: 'false'  

jobs:
  bootstrap-repository:
    runs-on: ubuntu-latest
    name: devsecops-init
    env:
      SAML_GITHUB_TOKEN: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }}
      GITHUB_WORKSPACE: ${{ github.workspace }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      APP_NAME: ${{ github.event.inputs.APP_NAME }}
      STACK: ${{ github.event.inputs.STACK_NAME }}
      SRC_FLAG: ${{github.event.inputs.INCLUDE_SAMPLE_SRC }}
    permissions:
      contents: write
      pull-requests: write 
  
    steps:
      - name: Pre-check
        run: |
          echo inputs are ${{  github.event.inputs.STACK_NAME }} ${{ github.event.inputs.INCLUDE_SAMPLE_SRC }}
     
######   Checkout repositories  #######    
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Checkout Java starter repo
        uses: actions/checkout@v3
        with:
          repository: DigitalInnovation/Cloud-DevSecOps-Pipeline-Java
          token: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }} 
          ref: refs/heads/main
          path: devsecops-starter
        if: ${{ env.STACK == 'Java' }}
        
      - name: Checkout Node starter repo
        uses: actions/checkout@v2
        with:
          repository: DigitalInnovation/Cloud-DevSecOps-Pipeline-Node
          token: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }}  
          ref: refs/heads/main
          path: devsecops-starter
        if: ${{env.STACK == 'Node' }}

######   ADD NECESSARY PIPELINE CONTENT  #######
      - name: Add necessary JAVA STARTER PIPELINE Workflows
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          
          mkdir -p ${REPO_PATH}/.github/workflows
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/java-maven_starter_pipeline.yml ${REPO_PATH}/.github/workflows/java-maven_starter_pipeline.yml
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/pipeline_insights.yml ${REPO_PATH}/.github/workflows/pipeline_insights.yml
        if: ${{env.STACK == 'Java' }}
        
      - name: Add necessary NODE STARTER PIPELINE Workflows 
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          mkdir -p ${REPO_PATH}/.github/workflows
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/npm_build_starter_pipeline.yml ${REPO_PATH}/.github/workflows/npm_build_starter_pipeline.yml
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/pipeline_insights.yml ${REPO_PATH}/.github/workflows/pipeline_insights.yml
        if: ${{ env.STACK == 'Node' }}

######   ADD SAMPLE CONTENT  #######
      - name: Add optional JAVA Sample Source Content 
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/java-maven-sample/* ${REPO_PATH}
        if: ${{env.SRC_FLAG == 'true' && env.STACK == 'Java'}}
        
      - name: Add optional Node Sample Source Content 
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/nodejs-sample/* ${REPO_PATH}
        if: ${{env.SRC_FLAG == 'true' && env.STACK == 'Node'}}
        
######   CLEAN UP POST PROCESSS and CREATE PULL REQUEST #######          
      - name: remove the Starter Repo Local Clone
        run: |
          rm -rf ${{ github.workspace }}/devsecops-starter
                    
      - name: Create Pull Request to add Starter Pipeline and sample source to build.
        uses: peter-evans/create-pull-request@v4
        with: 
          token: ${{secrets.GITHUB_TOKEN}} 
          branch: devsecops-bootstrap
          branch-suffix: random
          commit-message: "feat: bootstrapping repo run ${{ github.run_id }}"
          title: "automated-devsecops-repo-bootstrap-runid-${{ github.run_id }}"
          labels: |
            devsecops-init-starter-piepline-src
