#This is an initialization workflow for copying Node starter workflow and sample app (if required)
name: devsecops-init
on: 
  workflow_dispatch:
    inputs:
      STACK_NAME:
        description: 'Type in Java or Node'     
        required: true
        options: 
        - Node
        - Java
      
        default: 'Node'
      INCLUDE_SAMPLE_SRC:
        description: 'Do you need the sample source code to be included'     
        required: false
        options: 
        - 'false'
        - 'true'
        default: 'false' 
        

jobs:
  bootstrap-repository:
    runs-on: ubuntu-latest
    name: devsecops-init
    env:
      GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN}}
      GITHUB_WORKSPACE: ${{ github.workspace }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      APP_NAME: ${{ github.event.inputs.APP_NAME }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Checkout starter repo
        uses: actions/checkout@v2
        with:
          repository: DigitalInnovation/Cloud-DevSecOps-Pipeline-Node
          token: ${{ secrets.SAML_GITHUB_TOKEN}}
          ref: refs/heads/main
          path: devsecops-starter
          
      - name: Add necessary STARTER PIPELINE Workflows
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          mkdir -p ${REPO_PATH}/.github/workflows
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/npm_build_starter_pipeline.yml ${REPO_PATH}/.github/workflows/npm_build_starter_pipeline.yml
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/pipeline_insights.yml ${REPO_PATH}/.github/workflows/pipeline_insights.yml
          
      - name: Add optional Sample Source Content 
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/nodejs-sample/* ${REPO_PATH}
        if: ${{inputs.INCLUDE_SAMPLE_SRC == 'true'}}  
        
      - name: remove the Starter Repo Local Clone
        run: |
          ls -lart
          rm -rf ${{ github.workspace }}/devsecops-starter
          ls -lart
          git status

      - name: Create Pull Request to add Starter Pipeline and sample source to build.
        uses: peter-evans/create-pull-request@v4
        with: 
          token: ${{secrets.SAML_GITHUB_TOKEN }}
          branch: devsecops-bootstrap
          branch-suffix: random
          commit-message: "feat: bootstrapping repo run ${{ github.run_id }}"
          title: "automated-devsecops-repo-bootstrap-runid-${{ github.run_id }}"
          labels: |
            devsecops-init-starter-piepline-src

