name: Semgrep 

on:
  pull_request: {}
  workflow_dispatch: {}
  push:

jobs:
  call-semgrep:
    uses: DigitalInnovation/semgrep-appsec-workflow/.github/workflows/semgrep_webapps.yml@v2.1.7 
    #with:
      #fail-on: '<Value is either HIGH, MEDIUM or LOW to fail the build on having vulnerabilities with these severitites(Optional Parameter)>'
      #include-patterns: '<Patterns to include in scanning. Supply as comma-separated values(Optional Parameter)>'
      #exclude-patterns: '<Patterns to exclude from scanning. Supply as comma-separated values(Optional Parameter)>'  
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

   #DigitalInnovation/semgrep-appsec-workflow/.github/workflows/mobileapps.yml@v2.1.7 can be used for mobile apps
   
   #Please visit https://devopssec.engineering.mnscorp.net/Products/Semgrep-Code/CI-Integration/githubaction/ for more details on Semgrep.
